# Generated by Django 5.1.14 on 2026-05-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200)),
                ('speaker_handle', models.CharField(blank=True, max_length=500)),
                ('speaker_org', models.CharField(blank=True, max_length=200)),
                ('speaker_location', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('suggested_talk', models.CharField(blank=True, max_length=500)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_role', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
