# Generated by Django 5.0.6 on 2024-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalregistration',
            name='organization',
        ),
        migrations.AddField(
            model_name='generalregistration',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalregistration',
            name='telegramusername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalregistration',
            name='xhandle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
