# Generated by Django 5.0.6 on 2024-06-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_generalregistration_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalregistration',
            name='role',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
