# Generated by Django 5.0.6 on 2024-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_generalregistration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalregistration',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
