# Generated by Django 5.1.14 on 2026-08-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="URL-friendly identifier like 'main-stage', 'hall-2'", max_length=100, null=True)),
                ('embed_url', models.URLField(blank=True, help_text="YouTube embed URL for this hall's live stream")),
                ('is_live', models.BooleanField(default=False, help_text='When true and embed_url is set, the public live page shows the stream')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='schedules.conference')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('slug', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel Discussion'), ('break', 'Break'), ('registration', 'Registration'), ('networking', 'Networking')], default='talk', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('speaker', models.CharField(blank=True, max_length=200)),
                ('speaker_bio', models.TextField(blank=True)),
                ('speaker_image', models.URLField(blank=True)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
                ('video_thumbnail', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedules.conference')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedules.hall')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
